/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.cashforward.ui.options;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.cashforward.ui.internal.options.UIOptions;

final class EntryPanel extends javax.swing.JPanel {

    private final EntryOptionsPanelController controller;

    EntryPanel(final EntryOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        cbRequireLabel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                controller.changed();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbRequireLabel = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(cbRequireLabel, org.openide.util.NbBundle.getMessage(EntryPanel.class, "EntryPanel.cbRequireLabel.text")); // NOI18N
        cbRequireLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRequireLabelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(cbRequireLabel)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(cbRequireLabel)
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbRequireLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRequireLabelActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cbRequireLabelActionPerformed

    void load() {
        cbRequireLabel.setSelected(UIOptions.paymentsRequireLabel());
    }

    void store() {
        UIOptions.setPaymentsRequireLabel(cbRequireLabel.isSelected());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbRequireLabel;
    // End of variables declaration//GEN-END:variables
}
