/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.cashforward.ui.scenario;

import org.cashforward.ui.UIContext;
import java.io.Serializable;
import java.util.Collection;
import java.util.logging.Logger;
import org.cashforward.model.PaymentSearchCriteria;
import org.cashforward.ui.task.PaymentFilter;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
final class ScenarioTopComponent extends TopComponent {

    private static ScenarioTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";

    Lookup.Result filterNotifier =
            UIContext.getDefault().lookupResult(PaymentFilter.class);    
    PaymentFilter paymentFilter =
            UIContext.getDefault().getPaymentFilter();
    
    private static final String PREFERRED_ID = "ScenarioTopComponent";

    private ScenarioTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(ScenarioTopComponent.class, "CTL_ScenarioTopComponent"));
        setToolTipText(NbBundle.getMessage(ScenarioTopComponent.class, "HINT_ScenarioTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
    
        scenarioPanel.setPayments(UIContext.getDefault().getPayments());
        scenarioPanel.setPaymentFilter(paymentFilter);
        
        filterNotifier.addLookupListener(new LookupListener() {

            public void resultChanged(LookupEvent event) {
                Lookup.Result r = (Lookup.Result) event.getSource();
                Collection c = r.allInstances();
                if (!c.isEmpty()) {
                    PaymentFilter filter = 
                            (PaymentFilter) c.iterator().next();
                    //now what? set dates? only if non-null 
                    if (filter.getDateEnd() != null){
                       ScenarioTopComponent.this.
                               scenarioPanel.setPaymentFilter(paymentFilter);
                    }
                    
                }
            }
        });
        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scenarioPanel = new org.cashforward.ui.scenario.ScenarioPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scenarioPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scenarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.cashforward.ui.scenario.ScenarioPanel scenarioPanel;
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized ScenarioTopComponent getDefault() {
        if (instance == null) {
            instance = new ScenarioTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the ScenarioTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized ScenarioTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(ScenarioTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof ScenarioTopComponent) {
            return (ScenarioTopComponent) win;
        }
        Logger.getLogger(ScenarioTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return ScenarioTopComponent.getDefault();
        }
    }
}
