/*
 * PaymentMiniView.java
 *
 * Created on June 20, 2008, 10:49 PM
 */

package org.cashforward.ui.payment;

import ca.odell.glazedlists.EventList;
import org.cashforward.model.Label;
import org.cashforward.model.Payee;
import org.cashforward.model.Payment;

/**
 * Experimetal layout of a small Payment interface.
 * 
 * @author  Bill
 */
public class PaymentMiniView extends javax.swing.JPanel {

    Payment payment;
    EventList<Payee> payees;
    
    /** Creates new form PaymentMiniView */
    public PaymentMiniView() {
        initComponents();
    }
    
    public void setPayees(EventList<Payee>payees){
        this.payees = payees;
        //payeeCombo.setModel(new EventListComboBoxModel(payees));
    }

    public void setLabels(EventList<Label>labels){
        
    }
    
    public void setPayment(Payment payment) {
       this.payment = payment;
       descriptionText.setText(payment.getDescription());
       //paymentAmountCombo.getCalculator().setDisplayText(
         //      Float.toString(payment.getAmount()));
       //payeeCombo.setEditable(true);
       //payeeCombo.setSelectedItem(payment.getPayee());
       //spaymentDateChooser.setDate(payment.getStartDate());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        payeeLbl = new javax.swing.JLabel();
        amountLbl = new javax.swing.JLabel();
        descriptionText = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(PaymentMiniView.class, "PaymentMiniView.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        jLabel7.setText(org.openide.util.NbBundle.getMessage(PaymentMiniView.class, "PaymentMiniView.jLabel7.text")); // NOI18N

        labelLbl.setText(org.openide.util.NbBundle.getMessage(PaymentMiniView.class, "PaymentMiniView.labelLbl.text")); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        payeeLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        payeeLbl.setText(org.openide.util.NbBundle.getMessage(PaymentMiniView.class, "PaymentMiniView.payeeLbl.text")); // NOI18N

        amountLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountLbl.setForeground(new java.awt.Color(255, 0, 0));
        amountLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        amountLbl.setText(org.openide.util.NbBundle.getMessage(PaymentMiniView.class, "PaymentMiniView.amountLbl.text")); // NOI18N

        descriptionText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        descriptionText.setText(org.openide.util.NbBundle.getMessage(PaymentMiniView.class, "PaymentMiniView.descriptionText.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(payeeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                    .addComponent(descriptionText, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payeeLbl)
                    .addComponent(amountLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionText)
                .addContainerGap(5, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText(org.openide.util.NbBundle.getMessage(PaymentMiniView.class, "PaymentMiniView.jLabel5.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(jLabel5))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLbl;
    private javax.swing.JLabel descriptionText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelLbl;
    private javax.swing.JLabel payeeLbl;
    // End of variables declaration//GEN-END:variables

}
