/*
 * PaymentDetailPanel.java
 *
 * Created on May 17, 2008, 9:49 PM
 */
package org.cashforward.ui.payment;

import ca.odell.glazedlists.EventList;
import ca.odell.glazedlists.event.ListEvent;
import ca.odell.glazedlists.event.ListEventListener;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.cashforward.model.Label;
import org.cashforward.model.Payee;
import org.cashforward.model.Payment;

/**
 *
 * @author  Bill
 */
public class PaymentDetailPanel extends javax.swing.JPanel {

    Payment payment;

    /** Creates new form PaymentDetailPanel */
    public PaymentDetailPanel() {
        initComponents();
        this.paymentAmountCombo.getCalculator().setDisplayFormat(
                NumberFormat.getCurrencyInstance());
    }

    public void setPayees(EventList<Payee> payees) {
        payeeCombo.setModel(new EventListComboBoxModel(payees));
    }

    public void setLabels(EventList<Label> labels) {
        this.labelList.setModel(new EventListComboBoxModel(labels));
    }

    public void setOccurences(List<Label> occurences) {
    }

    public void setPayment(Payment payment) {
        this.payment = payment;
        setIsDeposit(payment.getAmount() >= 0);

        descriptionText.setText(payment.getDescription());
        paymentAmountCombo.getCalculator().setDisplayText(
                Float.toString(payment.getAmount()));
        payeeCombo.setEditable(true);
        payeeCombo.setSelectedItem(payment.getPayee());
        paymentDateChooser.setDate(payment.getStartDate());
        labelList.setSelectedObjects(payment.getLabels().toArray());
    }

    public Payment getPayment() {
        //set up the payment
        payment.setDescription(descriptionText.getText());
        payment.setAmount(getAmount());

        //set payee
        Object payee = payeeCombo.getSelectedItem();
        if (payee instanceof String) {
            payee = new Payee(payee.toString());
        }
        payment.setPayee((Payee) payee);

        //set label
        payment.getLabels().clear();
        Object[] selectedLabels = labelList.getSelectedObjects();
        for (int i = 0; i < selectedLabels.length; i++) {
            if (selectedLabels[i] instanceof Label) 
                payment.addLabel((Label) selectedLabels[i]);
            else 
                payment.addLabel(new Label((String)selectedLabels[i]));
        }


        payment.setStartDate(paymentDateChooser.getDate());
        return this.payment;
    }

    private void setIsDeposit(boolean isDeposit){
        cbDeposit.setSelected(isDeposit);
        cbBill.setSelected(!isDeposit);
    }
    
    private boolean isDeposit(){
       return cbDeposit.isSelected();
    }

    private float getAmount(){
       float amount = Float.parseFloat(
                paymentAmountCombo.getCalculator().getDisplayText());

       if (!isDeposit())
            amount = -1 * amount;

       return amount;
    }
    
    private class EventListComboBoxModel extends DefaultComboBoxModel {

        EventList source;

        public EventListComboBoxModel(EventList source) {
            super();
            this.source = source;
            source.addListEventListener(new ListEventListener<Payee>() {
                public void listChanged(ListEvent<Payee> event) {
                    EventListComboBoxModel.this.fireContentsChanged(
                            EventListComboBoxModel.this,0,event.getSourceList().size());
                }
            });
        }

        public Object getElementAt(int index) {
            Object retValue;
            retValue = source.get(index);
            return retValue;
        }

        public int getSize() {
            int retValue;
            retValue = source.size();
            return retValue;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        descriptionText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        labelList = new com.jidesoft.combobox.CheckBoxListComboBox();
        jLabel5 = new javax.swing.JLabel();
        paymentDateChooser = new com.jidesoft.combobox.DateComboBox();
        jLabel3 = new javax.swing.JLabel();
        payeeCombo = new com.jidesoft.swing.AutoCompletionComboBox();
        jLabel4 = new javax.swing.JLabel();
        paymentAmountCombo = new com.jidesoft.combobox.CalculatorComboBox();
        cbDeposit = new javax.swing.JRadioButton();
        cbBill = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(PaymentDetailPanel.class, "PaymentDetailPanel.jLabel1.text")); // NOI18N

        descriptionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTextActionPerformed(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(PaymentDetailPanel.class, "PaymentDetailPanel.jLabel2.text")); // NOI18N

        labelList.setPreferredSize(new java.awt.Dimension(119, 20));

        jLabel5.setText(org.openide.util.NbBundle.getMessage(PaymentDetailPanel.class, "PaymentDetailPanel.jLabel5.text")); // NOI18N

        paymentDateChooser.setPreferredSize(new java.awt.Dimension(92, 20));

        jLabel3.setText(org.openide.util.NbBundle.getMessage(PaymentDetailPanel.class, "PaymentDetailPanel.jLabel3.text")); // NOI18N

        payeeCombo.setStrict(false);

        jLabel4.setText(org.openide.util.NbBundle.getMessage(PaymentDetailPanel.class, "PaymentDetailPanel.jLabel4.text")); // NOI18N

        paymentAmountCombo.setPreferredSize(new java.awt.Dimension(119, 20));

        buttonGroup1.add(cbDeposit);
        cbDeposit.setText(org.openide.util.NbBundle.getMessage(PaymentDetailPanel.class, "PaymentDetailPanel.cbDeposit.text")); // NOI18N
        cbDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDepositActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbBill);
        cbBill.setText(org.openide.util.NbBundle.getMessage(PaymentDetailPanel.class, "PaymentDetailPanel.cbBill.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(PaymentDetailPanel.class, "PaymentDetailPanel.jLabel6.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paymentDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paymentAmountCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                    .addComponent(descriptionText, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(labelList, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(payeeCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbBill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDeposit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbDeposit)
                    .addComponent(cbBill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(paymentAmountCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(payeeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(descriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void descriptionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTextActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_descriptionTextActionPerformed

private void cbDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDepositActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_cbDepositActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cbBill;
    private javax.swing.JRadioButton cbDeposit;
    private javax.swing.JTextField descriptionText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private com.jidesoft.combobox.CheckBoxListComboBox labelList;
    private com.jidesoft.swing.AutoCompletionComboBox payeeCombo;
    private com.jidesoft.combobox.CalculatorComboBox paymentAmountCombo;
    private com.jidesoft.combobox.DateComboBox paymentDateChooser;
    // End of variables declaration//GEN-END:variables
}
