/*
 * PaymentTaskPanel.java
 *
 * Created on May 17, 2008, 9:18 PM
 */

package org.cashforward.ui.task;

import java.util.Collection;
import org.cashforward.model.Payee;
import org.cashforward.model.Payment;
import org.cashforward.ui.UIContext;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;

/**
 *
 * @author  Bill
 */
public class PaymentTaskPanel extends javax.swing.JPanel 
    implements LookupListener{

    private Lookup.Result paymentNotifier = null;
    private Lookup.Result payeeNotifier = null;
    
    /** Creates new form PaymentTaskPanel */
    public PaymentTaskPanel() {
        initComponents();
        
        paymentNotifier = UIContext.getDefault().lookupResult(Payment.class);
        paymentNotifier.addLookupListener (this);
        
        payeeNotifier = UIContext.getDefault().lookupResult(Payee.class);
        payeeNotifier.addLookupListener(new LookupListener() {
            public void resultChanged(LookupEvent arg0) {
                paymentDetail.setPayees(UIContext.getDefault().getPayees());
            }
        });
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentDetail = new org.cashforward.ui.payment.PaymentDetailPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paymentDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paymentDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.cashforward.ui.payment.PaymentDetailPanel paymentDetail;
    // End of variables declaration//GEN-END:variables

   public void resultChanged(LookupEvent lookupEvent) {
       Lookup.Result r = (Lookup.Result) lookupEvent.getSource();
       Collection c = r.allInstances();
        if (!c.isEmpty()) {
            System.out.println("setting payment");
            Payment payment = (Payment) c.iterator().next();
            paymentDetail.setPayment(payment);
        } 
    }

}
